### PR TITLE
transcritical versions of exisiting subcritical heat pumps

### PR DESCRIPTION
**Pull request by bilwint**
#5 
Implemented Transcritical versions
- created trans models
- created input parameters
- created topologies
- updated the models in variables.py
- implemented code in hp_dashboard.py

In transcritical versions, especially with intermediate pressure or temperature states, there is a chance of encountering an error (negative mass flow rates) when the temperature out of trans_HE (T_A0) falls below a certain point (where T_A0 is directly related to the heat sink backflow through ttd_l). This happens because the state after mid-expansion will be outside the saturated liquid curve. Outside the saturated liquid curve, the value of enthalpy increases with expansion, causing the outlet temperature after expansion to increase slightly. To avoid this, I calculated the possible minimum value of T_A0 from the enthalpy of saturated liquid at intermediate pressure and gave  this value to the min_value to the slider heat sink backflow. 
The code seems bulky. If you have a better idea, please suggest it and I will work on it

To do later
The models works perfectly with the working fluid within the params. They also need to be tested with other working fluids. Additionally, the off-design conditions need to be checked once the generalized off-design method is completed.

### CODE REVIEW

**Comment by jfreissmann** [comment]
We are working through your changes and one thing that we think should be changed are the transcritical topology schemas. As they are identical to the subcritical ones, they are pretty redundant and just use up space. A better way would be an implementation within the dashboard, that fetches the right topology schema, no matter if the process is trans- or subcritical.

To avoid having all these redundant files in the repo history and therefore using up space, I think the commit that generates the topology files should be fully removed. The `git rebase` method allows for such a maneuver, but should be used cautiously, as changes are lost forever when they are removed. This [StackOverflow answer](https://stackoverflow.com/a/13389977) lays out the exact method to use for removing one specific commit from a repositories history. The `<commit-id>` should be replaced by the individual 7 digit SHA-1 hash of your commit (in this case `43cb384` if I am not mistaken, but please verify that for yourself). Maybe save a backup of your changes before following through with the rebasing.

If you have any more questions about that, feel free to reply to this comment.

Best regards.

**Comment by bilwint** [comment]
I did as above. I think it worked perfectly. Now I can push, right ?


rebase

**Comment by jfreissmann** [comment]
That looks correct to me. Did you verify that the other changes are unaffected?

**Comment by bilwint** [comment]
yes, seems to be okay. So if I push, it will replace the existing commits in Git, right?

**Comment by jfreissmann** [comment]
Yes, that is what I would expect. Maybe you have to use `git push --force`, but I am not 100% sure.

**Comment by bilwint** [comment]
can you check now, because now its showing total 11 commits ahead from your repo

**Comment by jfreissmann** [comment]
Yeah, unfortunately, that looks wrong. The commits got new hashes, so maybe the merging with your fork of the repository could not understand that these commits are the same and should be aligned.

I am not sure what the best follow up for this problem is. The somewhat tedious but most straightforward way would be saving your changes in a backup, deleting your fork, creating a new one and adding and commiting the changes you want you keep by hand. Most likely there is a more professional way with Git, but we are not confindent with a solution after this did not work. What do you think?

**Pull request closed without merging**
