### PR TITLE
Cascading heat pump models

### PR DESCRIPTION
**Pull request by bilwint**
#6 
Added cascaded heat pump models of existing single cycle heat pump models.

Created child class of new cascade heat pump models
Created corresponding input parameter file
Created topologie flow sheet as .svg file for light and dark mode
Added the class to the `hp_models` dictionairy of `variables.py`
updated `parameter.py`
updated `__init__.py`

### CODE REVIEW

**Comment by jfreissmann** [comment]
Damn, thank you very much for all of the work. I played around with it for a while and it mostly looks great. I will merge it into main.

I got three things from my experience with the dashboard with the new models:

- The process variation of sub- or transcritical probably should be a separate options, as the menu is pretty cluttered with repetition
- Similarly, the cascading heat pumps are all in one selection drop down menu, which is pretty overwhelming I feel
- We need to dynamically allow for two transcritical pressures to be set in cascading trans heat pumps (this technically is a bug for now, as those models do not work)

In a far future, I think it would be great to have different cycle topologies in the low and high temperature cycle, but the models are still great for now. Also, my limited testing has confirmed to me again, that I should finally create automated test to at least check if all models run with default parameters 😅

**Comment by bilwint** [comment]
hi @jfreissmann,

Did you mean by the third point  that we have to consider both cycles in the cascading heat pump as transcritical ?. 

I also agree with you, the selection of heat pump has become messy.

**Comment by jfreissmann** [comment]
> Did you mean by the third point that we have to consider both cycles in the cascading heat pump as transcritical ?.

That seemed to be a misunderstanding on my part. It wasn't quite clear to me, if in transcritical cascading heat pump models both cycles are using transcritical processes or only one. After looking into the models, i realized that only the high temperature cycle is transcritical, which also makes sense to me. Maybe we should emphasize that somehow, so that users get that as well.

**Comment by bilwint** [comment]
ok,

**Pull request merged**
